import Head from 'next/head'
import { useState } from 'react';
import Header from '../components/Header'
import PricingCard from '../components/PricingCard'

export default function Home() {
  const allData = {
    "monthly":[
      {
      "id":"y0",
      "plantype":"Standard",
      "price":"$12",
      "unit":"month",
      "buttonlabel":"Get Started",
      "services":[
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },  
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        }  
      ]
    },
      {
      "id":"y1",
      "plantype":"Pro",
      "price":"$70",
      "unit":"month",
      "buttonlabel":"Schedule Demo",
      "services":[
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },    
      ]
    },
    ],
    "daily":[
      {
      "id":"x0",  
      "plantype":"Standard",
      "price":"$3",
      "unit":"daily",
      "buttonlabel":"Get Started",
      "services":[
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
      ]
    },
      {
      "id":"x1",
      "plantype":"Pro",
      "price":"$58",
      "unit":"daily",
      "buttonlabel":"Schedule Demo",
      "services":[
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
      ]
    },
    ],
    "yearly":[
      {
      "id":"z0",
      "plantype":"Standard",
      "price":"$155",
      "unit":"yearly",
      "buttonlabel":"Get Started",
      "services":[
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
      ]
    },
      {
      "id":"z1",
      "plantype":"Pro",
      "price":"$2500",
      "unit":"yearly",
      "buttonlabel":"Schedule Demo",
      "services":[
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },
        {
          "item":"Mail Service Auth"
        },    
      ]
    },
    ],
    
  };

  const [cardData, setCardData] = useState(allData.monthly);

  const handleMonthly = () =>{
    setCardData(allData.monthly)
  };
  
  const handleDaily = () =>{
    setCardData(allData.daily)
  };
 
  const handleYearly = () =>{
    setCardData(allData.yearly)
  };

  return (
    <div>
      <Head>
        <title>Tryp Design</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>
        <section className='bg-[#050d35] pt-20 pb-1 md:py-20 md:pb-50'>
          <div className='relative'>
            <div className='pb-3 text-[#356dc8] w-full'>
              <p className='text-lg font-semibold text-center'>AI Powered Tool</p>
            </div>
            <div className='w-full pb-16 text-white'>
              <p className='text-center text-5xl font-bold'>Let&apos;s create the perfect 
              <br/><span className='leading-normal'>holiday for you.</span></p>
            </div>
          </div>
          <div className='flex justify-center bg-[#050d35] mt-5 mb-40'>
            <div className='flex items-center border-2 border-gray-700 rounded-full 
              text-gray-500 justify-around '>
              <button className='cursor-pointer font-semibold rounded-l-full py-2 px-8 
              focus:bg-[#356dc8] focus:text-white hover:text-white' onClick={handleDaily}>
              Daily</button>
              <button className='cursor-pointer font-semibold py-2 px-8 focus:bg-[#356dc8] focus:text-white
              hover:text-white'
              onClick={handleMonthly}>
              Monthly</button>
              <button className='cursor-pointer font-semibold rounded-r-full focus:bg-[#356dc8]
               focus:text-white py-2 px-8 hover:text-white' onClick={handleYearly}>
              Yearly</button>
            </div>
          </div>
        </section>
        <section className='max-w-4xl px-8 pt-4 mx-auto md:-mt-48'>
          <div className='grid md:grid-cols-2 gap-x-20 gap-y-10 last:pb-40'>
            {cardData?.map((val) => (
              <PricingCard 
                key={val.id}
                plantype={val.plantype}
                price={val.price}
                unit={val.unit}
                buttonlabel={val.buttonlabel}
                services={val.services}
              />

            ))}
          </div>
        </section>
        
      </main>
    </div>
  )
}
